Resources:
  TwiqqsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.twiqqsTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: twiqqsId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: twiqqsId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST