Resources:
  TwiqqsMessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.twiqqsMessagesTableName}
      AttributeDefinitions:
        - AttributeName: topic
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
      KeySchema:
        - AttributeName: topic
          KeyType: HASH
        - AttributeName: messageId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  TwiqqsTopicsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.twiqqsTopicsTableName}
      AttributeDefinitions:
        - AttributeName: topic
          AttributeType: S
      KeySchema:
        - AttributeName: topic
          KeyType: HASH´
      BillingMode: PAY_PER_REQUEST