Resources:
  TwiqqsMessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.twiqqsMessagesTableName}
      AttributeDefinitions:
        - AttributeName: topic
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
      KeySchema:
        - AttributeName: topic
          KeyType: HASH
        - AttributeName: messageId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - 
          Key: 'Project'
          Value: 'twiqqs'
  TwiqqsTopicsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.twiqqsTopicsTableName}
      AttributeDefinitions:
        - AttributeName: topic
          AttributeType: S
      KeySchema:
        - AttributeName: topic
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - 
          Key: 'Project'
          Value: 'twiqqs'
  TwiqqsConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.twiqqsConnectionsTableName}
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification: 
        AttributeName: timeToLive
        Enabled: true
      Tags:
        - 
          Key: 'Project'
          Value: 'twiqqs'